---
- name: Ensure postfix is installed.
  package:
    name: postfix
    state: present

- name: Update Postfix configuration.
  template:
    src: /etc/ansible/roles/postfix/templates/main.cf.j2
    dest: /etc/postfix/main.cf
  notify: restart postfix

- name: Ensure postfix is started and enabled at boot.
  service:
    name: postfix
    state: "{{ service_state }}"
    enabled: "{{ service_enabled }}"
